/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Beneficiary.OlgAgeHome;

import userinterface.Beneficiary.BeneficiaryPersonViewJPanel;
import userinterface.Beneficiary.Homeless.*;
import Business.EcoSystem;
//import userinterface.Hospital.*;
import Business.Enterprise.Enterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
//import Business.Organization.ClinicOrganization;
import Business.Organization.OldAgeOrganization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import utility.Validator;

/**
 *
 * @author raunak
 */
public class OldAgeHomePersonJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;    
    private OldAgeOrganization organization;    
    private Enterprise enterprise;    
    private EcoSystem business;
    private StateNetwork state;
    private CountryNetwork country;
    private ImageIcon photo;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public OldAgeHomePersonJPanel(JPanel userProcessContainer, UserAccount account, OldAgeOrganization organization, Enterprise enterprise, StateNetwork network, CountryNetwork cNetwork, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        this.organization = organization;
        populateTable(organization);
        this.state = network;
        this.country = cNetwork;
        TextArea.enable(false);
          populateComboBox();
        // populateOrganizationEmpComboBox();
    }
    public void populateComboBox() {
        reqComboBox.removeAllItems();
        reqComboBox.addItem("White American");
        reqComboBox.addItem("African");
        reqComboBox.addItem("Asian");
        reqComboBox.addItem("Native Hawaiians");
        reqComboBox.addItem("Middle Eastern");
        reqComboBox.addItem("Others");
    }

//    public void populateOrganizationComboBox(){
//        organizationJComboBox.removeAllItems();
//        
//        for (Role role : organization.getSupportedRole()){
//            organizationJComboBox.addItem(role);
//        }
//    }
//    public void populateOrganizationEmpComboBox(){
//        organizationEmpJComboBox.removeAllItems();
//        
//        for (Role role : organization.getSupportedRole()){
//            organizationEmpJComboBox.addItem(role);
//        }
//    }
    private void populateTable(OldAgeOrganization organization) {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Person person : organization.getPersonList().getPersonList()) {
            
            Object[] row = new Object[7];
            row[0] = person.getPersonId();
            row[1] = person.getName();
            row[2] = person.getAge();
            row[3] = person.getSex();
            row[4] = person.getEthnicity();
            row[5] = person.getDateOfJoining();
            row[6] = person.getEducationBackground();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpReasons = new javax.swing.ButtonGroup();
        btnGrpEducationBackGround = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        btnCreatePerson = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ARadioButton = new javax.swing.JRadioButton();
        BRadioButton2 = new javax.swing.JRadioButton();
        CRadioButton3 = new javax.swing.JRadioButton();
        ORadioButton4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdBtnHighschoolGrad = new javax.swing.JRadioButton();
        rdBtnCollegeGrad = new javax.swing.JRadioButton();
        rdBtnUneducated = new javax.swing.JRadioButton();
        rdBtnMale = new javax.swing.JRadioButton();
        rdBtnFemale = new javax.swing.JRadioButton();
        rdBtnOthers = new javax.swing.JRadioButton();
        reqComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        picText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(71, 79, 112));

        organizationJTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        organizationJTable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        organizationJTable.setForeground(new java.awt.Color(71, 79, 112));
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Sex", "Date Of Joining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 850, 92));

        btnCreatePerson.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCreatePerson.setForeground(new java.awt.Color(71, 79, 112));
        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });
        add(btnCreatePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 180, 50));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(71, 79, 112));
        btnBack.setText("<< Back");
        btnBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 120, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 79, 112));
        jLabel2.setText("*Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 50, -1));

        nameJTextField.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(71, 79, 112));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 126, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 79, 112));
        jLabel4.setText("Person Details");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 220, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 79, 112));
        jLabel5.setText("Create Person");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 220, 30));

        ageTextField.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ageTextField.setForeground(new java.awt.Color(71, 79, 112));
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 130, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 79, 112));
        jLabel1.setText("*Age:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 50, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(71, 79, 112));
        jLabel6.setText("*Reason For Joining");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        ARadioButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ARadioButton.setForeground(new java.awt.Color(71, 79, 112));
        ARadioButton.setText("Individual and relational factors");
        ARadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARadioButtonActionPerformed(evt);
            }
        });
        add(ARadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        BRadioButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BRadioButton2.setForeground(new java.awt.Color(71, 79, 112));
        BRadioButton2.setText("Economic Issues");
        BRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRadioButton2ActionPerformed(evt);
            }
        });
        add(BRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        CRadioButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CRadioButton3.setForeground(new java.awt.Color(71, 79, 112));
        CRadioButton3.setText("System failures");
        CRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRadioButton3ActionPerformed(evt);
            }
        });
        add(CRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, -1, -1));

        ORadioButton4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ORadioButton4.setForeground(new java.awt.Color(71, 79, 112));
        ORadioButton4.setText("Others");
        ORadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORadioButton4ActionPerformed(evt);
            }
        });
        add(ORadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, -1, -1));

        jScrollPane2.setForeground(new java.awt.Color(71, 79, 112));

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        TextArea.setRows(5);
        TextArea.setEnabled(false);
        jScrollPane2.setViewportView(TextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, -1, 52));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 79, 112));
        jLabel3.setText("*Sex:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 40, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(71, 79, 112));
        jLabel7.setText("Ethnicity:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 70, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(71, 79, 112));
        jLabel8.setText("*Education Background:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        rdBtnHighschoolGrad.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rdBtnHighschoolGrad.setForeground(new java.awt.Color(71, 79, 112));
        rdBtnHighschoolGrad.setText("Highschool Graduate");
        add(rdBtnHighschoolGrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        rdBtnCollegeGrad.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rdBtnCollegeGrad.setForeground(new java.awt.Color(71, 79, 112));
        rdBtnCollegeGrad.setText("College Graduate");
        add(rdBtnCollegeGrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        rdBtnUneducated.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rdBtnUneducated.setForeground(new java.awt.Color(71, 79, 112));
        rdBtnUneducated.setText("Uneducated");
        add(rdBtnUneducated, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, -1));

        buttonGroup1.add(rdBtnMale);
        rdBtnMale.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rdBtnMale.setForeground(new java.awt.Color(71, 79, 112));
        rdBtnMale.setText("Male");
        add(rdBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        buttonGroup1.add(rdBtnFemale);
        rdBtnFemale.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rdBtnFemale.setForeground(new java.awt.Color(71, 79, 112));
        rdBtnFemale.setText("Female");
        add(rdBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        buttonGroup1.add(rdBtnOthers);
        rdBtnOthers.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rdBtnOthers.setForeground(new java.awt.Color(71, 79, 112));
        rdBtnOthers.setText("Others");
        add(rdBtnOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        reqComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        reqComboBox.setForeground(new java.awt.Color(71, 79, 112));
        add(reqComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 110, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(71, 79, 112));
        jLabel9.setText("Description: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, -1, -1));

        btnUpload.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(71, 79, 112));
        btnUpload.setText("Upload ");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(71, 79, 112));
        jLabel10.setText("*Photo:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, -1, -1));

        btnViewDetails.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(71, 79, 112));
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(71, 79, 112));
        jLabel11.setText("* Mandatory Fields");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 760, -1, -1));

        picText.setForeground(new java.awt.Color(71, 79, 112));
        add(picText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        if (!(nameJTextField.getText().isEmpty())) {
            if (!(ageTextField.getText().isEmpty())) {
                if (((rdBtnMale.isSelected() || rdBtnFemale.isSelected() || rdBtnOthers.isSelected()))) {
                    
                    if (rdBtnCollegeGrad.isSelected() || rdBtnHighschoolGrad.isSelected() || rdBtnUneducated.isSelected()) {
                        
                        if (ARadioButton.isSelected() || BRadioButton2.isSelected() || CRadioButton3.isSelected() || ORadioButton4.isSelected()) {
                            
                            if (!(picText.getText().isEmpty())) {
                                try {
                                    //SimpleDateFormat date = new SimpleDateFormat("MM/dd/yyyy");
                                    //ClinicOrganization organization = (ClinicOrganization) organizationEmpJComboBox.getSelectedItem();
                                    String name = nameJTextField.getText();
                                    int age = Integer.parseInt(ageTextField.getText());
                                    String ethnicity = (String) reqComboBox.getSelectedItem();
                                    
                                    String sex = null;
                                    if (rdBtnMale.isSelected()) {
                                        sex = "Male";
                                    } else if (rdBtnFemale.isSelected()) {
                                        sex = "Female";
                                    } else if (rdBtnFemale.isSelected()) {
                                        sex = "Others";
                                    }
                                    String educationBG = null;
                                    if (rdBtnCollegeGrad.isSelected()) {
                                        educationBG = "College Graduate";
                                    } else if (rdBtnHighschoolGrad.isSelected()) {
                                        educationBG = "HighSchool Graduate";
                                    } else if (rdBtnUneducated.isSelected()) {
                                        educationBG = "Uneducated";
                                    }
                                    
                                    String reason = null;
                                    if (ARadioButton.isSelected()) {
                                        reason = "Individual and relational factors";
                                    } else if (BRadioButton2.isSelected()) {
                                        reason = "Economic Issues";
                                    } else if (CRadioButton3.isSelected()) {
                                        reason = "Systems failures";
                                    } else if (ORadioButton4.isSelected()) {
                                        reason = "Others";
                                    }
                                    
                                    String reasonDescription = TextArea.getText();
                                   
                                    organization.getPersonList().createperson(name, age, reason, ethnicity, sex, educationBG, reasonDescription, photo);
                                     JOptionPane.showMessageDialog(null, "Person Created");
                                    nameJTextField.setText("");
                                    ageTextField.setText("");
                                    buttonGroup1.clearSelection();
                                    btnGrpEducationBackGround.clearSelection();
                                    btnGrpReasons.clearSelection();
                                    TextArea.setText("");
                                    picText.setText("");
                                    populateTable(organization);
                                } catch (NumberFormatException p) {
                                    JOptionPane.showMessageDialog(null, "Please enter Valid Age");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Please upload the picture", "Warning", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please Select the either of the options for Reason", "Warning", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Select education background option", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please Select male or female option", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter the age", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please enter the name", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void ARadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARadioButtonActionPerformed
        // TODO add your handling code here:
        TextArea.enable(true);
    }//GEN-LAST:event_ARadioButtonActionPerformed

    private void BRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRadioButton2ActionPerformed
        // TODO add your handling code here:
        TextArea.enable(true);
    }//GEN-LAST:event_BRadioButton2ActionPerformed

    private void CRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRadioButton3ActionPerformed
        // TODO add your handling code here:
        TextArea.enable(true);
    }//GEN-LAST:event_CRadioButton3ActionPerformed

    private void ORadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORadioButton4ActionPerformed
        // TODO add your handling code here:
        TextArea.enable(true);
    }//GEN-LAST:event_ORadioButton4ActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f1 = chooser.getSelectedFile();
        if (f1 != null) {
            try {
                Image pic = ImageIO.read(f1);
                pic = pic.getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);
                picText.setText(chooser.getSelectedFile().getPath());
                photo = new ImageIcon(pic);
                
            } catch (Exception e) {
                
            }
        } else {
            
            JOptionPane.showMessageDialog(null, "Please select a picture", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:

        int selectedrow = organizationJTable.getSelectedRow();
        
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row from table first to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Person p = (Person) organizationJTable.getValueAt(selectedrow, 1);
            BeneficiaryPersonViewJPanel muajp = new BeneficiaryPersonViewJPanel(userProcessContainer, p);
            userProcessContainer.add("HomelessPersonViewJPanel", muajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
        }

    }//GEN-LAST:event_btnViewDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ARadioButton;
    private javax.swing.JRadioButton BRadioButton2;
    private javax.swing.JRadioButton CRadioButton3;
    private javax.swing.JRadioButton ORadioButton4;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.ButtonGroup btnGrpEducationBackGround;
    private javax.swing.ButtonGroup btnGrpReasons;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JTextField picText;
    private javax.swing.JRadioButton rdBtnCollegeGrad;
    private javax.swing.JRadioButton rdBtnFemale;
    private javax.swing.JRadioButton rdBtnHighschoolGrad;
    private javax.swing.JRadioButton rdBtnMale;
    private javax.swing.JRadioButton rdBtnOthers;
    private javax.swing.JRadioButton rdBtnUneducated;
    private javax.swing.JComboBox reqComboBox;
    // End of variables declaration//GEN-END:variables
}
