/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Beneficiary.OlgAgeHome;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EntityEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.EducationOrganization;
import Business.Organization.HomelessOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.MNCOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.OldAgeOrganization;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BeneficiaryWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Beneficiary.Homeless.*;

/**
 *
 * @author prashantreddy
 */
public class OldAgeHomeRequestHelpJPanel extends javax.swing.JPanel {

        JPanel userProcessContainer;
    UserAccount account; 
   OldAgeOrganization organization; 
    Enterprise enterprise; 
    EcoSystem business;
     StateNetwork state;
    CountryNetwork country;
    /**
     * Creates new form RequestHelpJPanel
     */
    public OldAgeHomeRequestHelpJPanel(JPanel userProcessContainer, UserAccount account, OldAgeOrganization organization, Enterprise enterprise,StateNetwork network,CountryNetwork cNetwork, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        this.business=business;
        this.organization= organization;
        this.state=network;
        this.country=cNetwork;
        populateComboBox();
       
//        for (StateNetwork stateNetwork : country.getStateList()) {
//            for (Enterprise enterprise1 : stateNetwork.getEnterpriseDirectory().getEnterpriseList()) {
//                for (Organization organization1 : enterprise1.getOrganizationDirectory().getOrganizationList()) {
//                    reqComboBox.addItem(organization1.);
//                    
//                }
//                
//            }
//        }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noVolTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reqComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        transCheckbox = new javax.swing.JCheckBox();
        spaceCheckBox = new javax.swing.JCheckBox();
        noneCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        eventNameTextfield = new javax.swing.JTextField();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        jLabel1.setText("Request Type:");

        jLabel2.setText("Number of Volunteers Required");

        jLabel3.setText("Event Date ");

        jButton1.setText("Request Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Logistics");

        transCheckbox.setText("Transportaion");

        spaceCheckBox.setText("Space");

        noneCheckBox.setText("Not Required");

        jLabel5.setText("Event Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(transCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(spaceCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(noVolTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(dateField)
                                    .addComponent(reqComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eventNameTextfield)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(noneCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reqComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eventNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noVolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(transCheckbox)
                    .addComponent(spaceCheckBox)
                    .addComponent(noneCheckBox))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void populateComboBox()
{
     reqComboBox.removeAllItems();
     reqComboBox.addItem(Organization.RequestType.Education);
     reqComboBox.addItem(Organization.RequestType.Hospital);
     reqComboBox.addItem(Organization.RequestType.MNC);
     reqComboBox.addItem(Organization.RequestType.NGO);
     reqComboBox.addItem(Organization.RequestType.ANY);
}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        SimpleDateFormat dates = new SimpleDateFormat("MM/dd/yyyy");
       
        Organization.RequestType request = (Organization.RequestType) reqComboBox.getSelectedItem();
        int noVolunteer= Integer.parseInt(noVolTextField.getText());
        Date date= dates.parse(dateField.getText());
        String eventName = eventNameTextfield.getText();
        BeneficiaryWorkRequest requests= new BeneficiaryWorkRequest();
       requests.setEventDate(date);
       requests.setSenderOrganization(organization.getName()+ Organization.Type.OldAge);
      //if(Organization.RequestType.Education.getValue()==request.getValue())
      requests.setRequestType(request);
       requests.setEventName(eventName);
       requests.setNumberOfVolunteersRequest(noVolunteer);
    
       requests.setSender(account);
       requests.setStatus("Requested");
            System.out.println("type is"+request);
       if(request==Organization.RequestType.ANY)
       {
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
               if(enter instanceof EntityEnterprise){
           enterprise.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       else if(request==Organization.RequestType.Education)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof EducationOrganization)
               {
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
           }
       }
       else if(request==Organization.RequestType.Hospital)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof HospitalOrganization)
               {
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       else if(request==Organization.RequestType.MNC)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof MNCOrganization)
               {
                   System.out.println("userinterface MNC" );
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       else if(request==Organization.RequestType.NGO)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof NGOOrganization)
               {
                   
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       JOptionPane.showMessageDialog(null, "Help request complete");
        }
        catch(ParseException p)
        {
            JOptionPane.showMessageDialog(null, "Please enter date in MM/dd/yyyy format");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        
        Component[] componentArray=userProcessContainer.getComponents();
        OldAgeHomeRequestWorkAreaJPanel oldAgeRequestPanel =(OldAgeHomeRequestWorkAreaJPanel)userProcessContainer.getComponent(componentArray.length -1);
       // oldAgeRequestPanel.populateUpdatedTable();
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField eventNameTextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField noVolTextField;
    private javax.swing.JCheckBox noneCheckBox;
    private javax.swing.JComboBox reqComboBox;
    private javax.swing.JCheckBox spaceCheckBox;
    private javax.swing.JCheckBox transCheckbox;
    // End of variables declaration//GEN-END:variables
}
