/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Beneficiary.OlgAgeHome;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EntityEnterprise;
import Business.Enterprise.LogisticEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.EducationOrganization;
import Business.Organization.HomelessOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.MNCOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.OldAgeOrganization;
import Business.Organization.Organization;
import Business.Organization.TransportOrganization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BeneficiaryWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Beneficiary.Homeless.*;

/**
 *
 * @author prashantreddy
 */
public class OldAgeHomeRequestHelpJPanel extends javax.swing.JPanel {

        JPanel userProcessContainer;
    UserAccount account; 
   OldAgeOrganization organization; 
    Enterprise enterprise; 
    EcoSystem business;
     StateNetwork state;
    CountryNetwork country;
    /**
     * Creates new form RequestHelpJPanel
     */
    public OldAgeHomeRequestHelpJPanel(JPanel userProcessContainer, UserAccount account, OldAgeOrganization organization, Enterprise enterprise,StateNetwork network,CountryNetwork cNetwork, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        this.business=business;
        this.organization= organization;
        this.state=network;
        this.country=cNetwork;
        carBtn.setVisible(false);
        busBtn.setVisible(false);
        vanBtn.setVisible(false);
        noOfVehText.setVisible(false);
        noVehLabel.setVisible(false);
        typeLabel.setVisible(false);
        populateComboBox();
       
//        for (StateNetwork stateNetwork : country.getStateList()) {
//            for (Enterprise enterprise1 : stateNetwork.getEnterpriseDirectory().getEnterpriseList()) {
//                for (Organization organization1 : enterprise1.getOrganizationDirectory().getOrganizationList()) {
//                    reqComboBox.addItem(organization1.);
//                    
//                }
//                
//            }
//        }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noVolTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reqComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        eventNameTextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        reqBtn = new javax.swing.JRadioButton();
        notReqBtn = new javax.swing.JRadioButton();
        noOfVehText = new javax.swing.JTextField();
        noVehLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        carBtn = new javax.swing.JRadioButton();
        vanBtn = new javax.swing.JRadioButton();
        busBtn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        enterpriseLabel.setBackground(new java.awt.Color(51, 51, 255));
        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 154, 40));
        enterpriseLabel.setText("EnterPrise :");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 79, 112));
        jLabel1.setText("Request Type:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 79, 112));
        jLabel2.setText("Number of Volunteers Required");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 79, 112));
        jLabel3.setText("Event Date ");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(71, 79, 112));
        jButton1.setText("Request Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(71, 79, 112));
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 79, 112));
        jLabel5.setText("Event Name");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(71, 79, 112));
        jLabel7.setText("Event Details");

        detailTextArea.setColumns(20);
        detailTextArea.setRows(5);
        jScrollPane1.setViewportView(detailTextArea);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 79, 112));
        jLabel4.setText("Logistics");

        buttonGroup2.add(reqBtn);
        reqBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        reqBtn.setForeground(new java.awt.Color(71, 79, 112));
        reqBtn.setText("Required");
        reqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(notReqBtn);
        notReqBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        notReqBtn.setForeground(new java.awt.Color(71, 79, 112));
        notReqBtn.setText("Not Required");
        notReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notReqBtnActionPerformed(evt);
            }
        });

        noVehLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        noVehLabel.setForeground(new java.awt.Color(71, 79, 112));
        noVehLabel.setText("Number Of Vehicles");

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(71, 79, 112));
        typeLabel.setText("Type of vehicle");

        buttonGroup1.add(carBtn);
        carBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        carBtn.setForeground(new java.awt.Color(71, 79, 112));
        carBtn.setText("Car");
        carBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(vanBtn);
        vanBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        vanBtn.setForeground(new java.awt.Color(71, 79, 112));
        vanBtn.setText("Mini Van");

        buttonGroup1.add(busBtn);
        busBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        busBtn.setForeground(new java.awt.Color(71, 79, 112));
        busBtn.setText("Bus");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(71, 79, 112));
        jLabel6.setText("Pickup Time");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(71, 79, 112));
        jLabel8.setText("Pickup Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(278, 278, 278)
                                .addComponent(reqBtn)
                                .addGap(31, 31, 31)
                                .addComponent(notReqBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeLabel)
                                    .addComponent(noVehLabel)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(timeField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(noOfVehText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(addressText, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(carBtn)
                                                .addGap(18, 18, 18)
                                                .addComponent(vanBtn)))
                                        .addGap(18, 18, 18)
                                        .addComponent(busBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel7))
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(noVolTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(dateField)
                                        .addComponent(reqComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eventNameTextfield)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reqComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eventNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noVolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reqBtn)
                            .addComponent(notReqBtn)
                            .addComponent(jLabel4))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noVehLabel)
                            .addComponent(noOfVehText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carBtn)
                            .addComponent(vanBtn)
                            .addComponent(busBtn)
                            .addComponent(typeLabel))
                        .addGap(44, 44, 44)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents
public void populateComboBox()
{
     reqComboBox.removeAllItems();
     reqComboBox.addItem(Organization.RequestType.Education);
     reqComboBox.addItem(Organization.RequestType.Hospital);
     reqComboBox.addItem(Organization.RequestType.MNC);
     reqComboBox.addItem(Organization.RequestType.NGO);
     reqComboBox.addItem(Organization.RequestType.ANY);
}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        SimpleDateFormat dates = new SimpleDateFormat("MM/dd/yyyy");
        
        Organization.RequestType request = (Organization.RequestType) reqComboBox.getSelectedItem();
        int noVolunteer= Integer.parseInt(noVolTextField.getText());
        Date date= dates.parse(dateField.getText());
        String eventName = eventNameTextfield.getText();
        String eventDetails= detailTextArea.getText();
        
        BeneficiaryWorkRequest requests= new BeneficiaryWorkRequest();
       requests.setEventDate(date);
       requests.setSenderOrganization(organization);
            System.out.println("userss"+organization.getName());
      //if(Organization.RequestType.Education.getValue()==request.getValue())
      requests.setRequestType(request);
       requests.setEventName(eventName);
       requests.setEventDetails(eventDetails);
       requests.setNumberOfVolunteersRequest(noVolunteer);
    
       requests.setSender(account);
       requests.setStatus("Requested");
       if(reqBtn.isSelected())
       {
            int no = Integer.parseInt(noOfVehText.getText());
       requests.setLogisticRequest(false);
       if(carBtn.isSelected()){
           requests.setTypeOfVehicle("Car");
          
       }
       else if(vanBtn.isSelected()){
            requests.setTypeOfVehicle("Van");
       }
       else if(busBtn.isSelected()){
            requests.setTypeOfVehicle("Bus");
       }
       requests.setNoOfVehicle(no);
      
       }
       if(!requests.isLogisticRequest()){
        for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof TransportOrganization)
               {
                   System.out.println("sending to transport");
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
           }
       }
       System.out.println("type is"+request);
       if(request==Organization.RequestType.ANY)
       {
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
               if(enter instanceof EntityEnterprise){
           enter.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       else if(request==Organization.RequestType.Education)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof EducationOrganization)
               {
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
           }
       }
       else if(request==Organization.RequestType.Hospital)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof HospitalOrganization)
               {
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       else if(request==Organization.RequestType.MNC)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof MNCOrganization)
               {
                   System.out.println("userinterface MNC" );
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       else if(request==Organization.RequestType.NGO)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof NGOOrganization)
               {
                   
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       organization.getWorkQueue().getWorkRequestList().add(requests);
       JOptionPane.showMessageDialog(null, "Help request complete");
        }
        catch(NumberFormatException p){
            JOptionPane.showMessageDialog(null, "Enter integer value");
        }
        catch(ParseException p)
        {
            JOptionPane.showMessageDialog(null, "Please enter date in MM/dd/yyyy format");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        
        Component[] componentArray=userProcessContainer.getComponents();
        OldAgeHomeRequestWorkAreaJPanel oldAgeRequestPanel =(OldAgeHomeRequestWorkAreaJPanel)userProcessContainer.getComponent(componentArray.length -1);
       // oldAgeRequestPanel.populateUpdatedTable();
       
       oldAgeRequestPanel.populateWorkQueueTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void carBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBtnActionPerformed

    private void reqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtnActionPerformed
        // TODO add your handling code here:
        
        carBtn.setVisible(true);
        busBtn.setVisible(true);
        vanBtn.setVisible(true);
        noOfVehText.setVisible(true);
         noVehLabel.setVisible(true);
        typeLabel.setVisible(true);
    }//GEN-LAST:event_reqBtnActionPerformed

    private void notReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notReqBtnActionPerformed
        // TODO add your handling code here:
         carBtn.setVisible(false);
        busBtn.setVisible(false);
        vanBtn.setVisible(false);
        noOfVehText.setVisible(false);
         noVehLabel.setVisible(false);
        typeLabel.setVisible(false);
    }//GEN-LAST:event_notReqBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JRadioButton busBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton carBtn;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField eventNameTextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfVehText;
    private javax.swing.JLabel noVehLabel;
    private javax.swing.JTextField noVolTextField;
    private javax.swing.JRadioButton notReqBtn;
    private javax.swing.JRadioButton reqBtn;
    private javax.swing.JComboBox reqComboBox;
    private javax.swing.JTextField timeField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JRadioButton vanBtn;
    // End of variables declaration//GEN-END:variables
}
