/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Beneficiary.OlgAgeHome;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EntityEnterprise;
import Business.Enterprise.LogisticEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.EducationOrganization;
import Business.Organization.HomelessOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.MNCOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.OldAgeOrganization;
import Business.Organization.Organization;
import Business.Organization.TransportOrganization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BeneficiaryWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Beneficiary.Homeless.*;
import utility.Validator;

/**
 *
 * @author prashantreddy
 */
public class OldAgeHomeRequestHelpJPanel extends javax.swing.JPanel {

        JPanel userProcessContainer;
    UserAccount account; 
   OldAgeOrganization organization; 
    Enterprise enterprise; 
    EcoSystem business;
     StateNetwork state;
    CountryNetwork country;
    /**
     * Creates new form RequestHelpJPanel
     */
    public OldAgeHomeRequestHelpJPanel(JPanel userProcessContainer, UserAccount account, OldAgeOrganization organization, Enterprise enterprise,StateNetwork network,CountryNetwork cNetwork, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        this.business=business;
        this.organization= organization;
        this.state=network;
        this.country=cNetwork;
        carBtn.setVisible(false);
        busBtn.setVisible(false);
        vanBtn.setVisible(false);
        noOfVehText.setVisible(false);
        noVehLabel.setVisible(false);
        typeLabel.setVisible(false);
               addressText.setVisible(false);
        timeField.setVisible(false);
        timelabel.setVisible(false);
        addLabel.setVisible(false);
        populateComboBox();
       
//        for (StateNetwork stateNetwork : country.getStateList()) {
//            for (Enterprise enterprise1 : stateNetwork.getEnterpriseDirectory().getEnterpriseList()) {
//                for (Organization organization1 : enterprise1.getOrganizationDirectory().getOrganizationList()) {
//                    reqComboBox.addItem(organization1.);
//                    
//                }
//                
//            }
//        }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noVolTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reqComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        eventNameTextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        reqBtn = new javax.swing.JRadioButton();
        notReqBtn = new javax.swing.JRadioButton();
        noOfVehText = new javax.swing.JTextField();
        noVehLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        carBtn = new javax.swing.JRadioButton();
        vanBtn = new javax.swing.JRadioButton();
        busBtn = new javax.swing.JRadioButton();
        timelabel = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setBackground(new java.awt.Color(51, 51, 255));
        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 154, 40));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 79, 112));
        jLabel1.setText("Request Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 106, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 79, 112));
        jLabel2.setText("Number of Volunteers Required");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 168, -1, -1));

        noVolTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noVolTextFieldKeyPressed(evt);
            }
        });
        add(noVolTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 164, 126, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 79, 112));
        jLabel3.setText("Event Date ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 212, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(71, 79, 112));
        jButton1.setText("Request Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 598, -1, -1));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(71, 79, 112));
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 598, -1, -1));

        add(reqComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 102, 126, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 79, 112));
        jLabel5.setText("Event Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 136, -1, -1));
        add(eventNameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 132, 126, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(71, 79, 112));
        jLabel7.setText("Event Details");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 240, -1, -1));

        detailTextArea.setColumns(20);
        detailTextArea.setRows(5);
        jScrollPane1.setViewportView(detailTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 240, 232, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 79, 112));
        jLabel4.setText("Logistics");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 346, -1, -1));

        buttonGroup2.add(reqBtn);
        reqBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        reqBtn.setForeground(new java.awt.Color(71, 79, 112));
        reqBtn.setText("Required");
        reqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtnActionPerformed(evt);
            }
        });
        add(reqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 342, -1, -1));

        buttonGroup2.add(notReqBtn);
        notReqBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        notReqBtn.setForeground(new java.awt.Color(71, 79, 112));
        notReqBtn.setText("Not Required");
        notReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notReqBtnActionPerformed(evt);
            }
        });
        add(notReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 342, -1, -1));

        noOfVehText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noOfVehTextKeyPressed(evt);
            }
        });
        add(noOfVehText, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 448, 53, -1));

        noVehLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        noVehLabel.setForeground(new java.awt.Color(71, 79, 112));
        noVehLabel.setText("Number Of Vehicles");
        add(noVehLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 452, -1, -1));

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(71, 79, 112));
        typeLabel.setText("Type of vehicle");
        add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 411, -1, -1));

        buttonGroup1.add(carBtn);
        carBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        carBtn.setForeground(new java.awt.Color(71, 79, 112));
        carBtn.setText("Car");
        carBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBtnActionPerformed(evt);
            }
        });
        add(carBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 407, -1, -1));

        buttonGroup1.add(vanBtn);
        vanBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        vanBtn.setForeground(new java.awt.Color(71, 79, 112));
        vanBtn.setText("Mini Van");
        add(vanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 407, -1, -1));

        buttonGroup1.add(busBtn);
        busBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        busBtn.setForeground(new java.awt.Color(71, 79, 112));
        busBtn.setText("Bus");
        add(busBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 407, -1, -1));

        timelabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        timelabel.setForeground(new java.awt.Color(71, 79, 112));
        timelabel.setText("Pickup Time");
        add(timelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 496, -1, -1));
        add(timeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 492, 53, -1));

        addLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addLabel.setForeground(new java.awt.Color(71, 79, 112));
        addLabel.setText("Pickup Address");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 540, -1, -1));
        add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 536, 170, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 203, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
public void populateComboBox()
{
     reqComboBox.removeAllItems();
     reqComboBox.addItem(Organization.RequestType.Education);
     reqComboBox.addItem(Organization.RequestType.Hospital);
     reqComboBox.addItem(Organization.RequestType.MNC);
     reqComboBox.addItem(Organization.RequestType.NGO);
     reqComboBox.addItem(Organization.RequestType.ANY);
}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(reqComboBox.getSelectedItem().equals(null)||jDateChooser1.getDate().equals(null)||eventNameTextfield.getText().isEmpty()||detailTextArea.getText().isEmpty()||reqBtn.isSelected()||notReqBtn.isSelected())
{ 
        try
        {
            
        //SimpleDateFormat dates = new SimpleDateFormat("MM/dd/yyyy");
      
        Organization.RequestType request = (Organization.RequestType) reqComboBox.getSelectedItem();
        int noVolunteer= Integer.parseInt(noVolTextField.getText());
        //Date date= dates.parse(dateField.getText());
        Date d= jDateChooser1.getDate();
        String eventName = eventNameTextfield.getText();
        String eventDetails= detailTextArea.getText();
        
                 
         
        BeneficiaryWorkRequest requests= new BeneficiaryWorkRequest();
       requests.setEventDate(d);
       requests.setSenderOrganization(organization);
            //System.out.println("userss"+organization.getName());
      //if(Organization.RequestType.Education.getValue()==request.getValue())
      requests.setRequestType(request);
       requests.setEventName(eventName);
       requests.setEventDetails(eventDetails);
       requests.setNumberOfVolunteersRequest(noVolunteer);
    
       requests.setSender(account);
       requests.setStatus("Requested");
       if(reqBtn.isSelected())
       {
             SimpleDateFormat times = new SimpleDateFormat("hh:mm");
            int no = Integer.parseInt(noOfVehText.getText());
            Date time= times.parse(timeField.getText());
                 String address= addressText.getText();
       requests.setLogisticRequest(false);
       if(carBtn.isSelected()){
           requests.setTypeOfVehicle("Car");
          
       }
       else if(vanBtn.isSelected()){
            requests.setTypeOfVehicle("Van");
       }
       else if(busBtn.isSelected()){
            requests.setTypeOfVehicle("Bus");
       }
       requests.setNoOfVehicle(no);
         requests.setPickupTime(time);
                requests.setAddress(address);
       }
       if(!requests.isLogisticRequest()){
        for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof TransportOrganization)
               {
                   //System.out.println("sending to transport");
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
           }
       }
       System.out.println("type is"+request);
       if(request==Organization.RequestType.ANY)
       {
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
               if(enter instanceof EntityEnterprise){
           enter.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       else if(request==Organization.RequestType.Education)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof EducationOrganization)
               {
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
           }
       }
       else if(request==Organization.RequestType.Hospital)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof HospitalOrganization)
               {
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       else if(request==Organization.RequestType.MNC)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof MNCOrganization)
               {
                   System.out.println("userinterface MNC" );
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       else if(request==Organization.RequestType.NGO)
       {
           //enterprise.getOrganizationDirectory().getOrganizationList().
           for (Enterprise enter : state.getEnterpriseDirectory().getEnterpriseList()) {
           for (Organization organization1 : enter.getOrganizationDirectory().getOrganizationList()) {
               if(organization1 instanceof NGOOrganization)
               {
                   
                   organization1.getWorkQueue().getWorkRequestList().add(requests);
               }
           }
       }
       }
       organization.getWorkQueue().getWorkRequestList().add(requests);
       JOptionPane.showMessageDialog(null, "Help request complete");

        }
        catch(NumberFormatException p){
            JOptionPane.showMessageDialog(null, "Enter integer value");
        }
        catch(ParseException p)
        {
            JOptionPane.showMessageDialog(null, "Please enter time in hh:mm format");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

      
       else
{
    JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
}
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        
        Component[] componentArray=userProcessContainer.getComponents();
        OldAgeHomeRequestWorkAreaJPanel oldAgeRequestPanel =(OldAgeHomeRequestWorkAreaJPanel)userProcessContainer.getComponent(componentArray.length -1);
       // oldAgeRequestPanel.populateUpdatedTable();
       
       oldAgeRequestPanel.populateWorkQueueTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void carBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBtnActionPerformed

    private void reqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtnActionPerformed
        // TODO add your handling code here:
        
        carBtn.setVisible(true);
        busBtn.setVisible(true);
        vanBtn.setVisible(true);
        noOfVehText.setVisible(true);
         noVehLabel.setVisible(true);
        typeLabel.setVisible(true);
               addressText.setVisible(true);
        timeField.setVisible(true);
         timelabel.setVisible(true);
        addLabel.setVisible(true);
    }//GEN-LAST:event_reqBtnActionPerformed

    private void notReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notReqBtnActionPerformed
        // TODO add your handling code here:
         carBtn.setVisible(false);
        busBtn.setVisible(false);
        vanBtn.setVisible(false);
        noOfVehText.setVisible(false);
         noVehLabel.setVisible(false);
        typeLabel.setVisible(false);
               addressText.setVisible(false);
        timeField.setVisible(false);
         timelabel.setVisible(false);
        addLabel.setVisible(false);
    }//GEN-LAST:event_notReqBtnActionPerformed

    private void noVolTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noVolTextFieldKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, noVolTextField);
    }//GEN-LAST:event_noVolTextFieldKeyPressed

    private void noOfVehTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noOfVehTextKeyPressed
        // TODO add your handling code here:
         Validator.onlyInteger(evt, noOfVehText);
    }//GEN-LAST:event_noOfVehTextKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JRadioButton busBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton carBtn;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField eventNameTextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfVehText;
    private javax.swing.JLabel noVehLabel;
    private javax.swing.JTextField noVolTextField;
    private javax.swing.JRadioButton notReqBtn;
    private javax.swing.JRadioButton reqBtn;
    private javax.swing.JComboBox reqComboBox;
    private javax.swing.JTextField timeField;
    private javax.swing.JLabel timelabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JRadioButton vanBtn;
    // End of variables declaration//GEN-END:variables
}
