/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SignUp;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.SignUp.SignUpRequest;
import Business.SignUp.SignUpRequest.SignUpType;
import Business.SignUp.SignUpRequestCountry;
import Business.SignUp.SignUpRequestState;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vinya
 */
public class SignUpWelcome extends javax.swing.JPanel {

    /**
     * Creates new form SignUpWelcome
     */
    private JPanel container;
    private EcoSystem system;

    public SignUpWelcome(JPanel container, EcoSystem system) {
        initComponents();
        this.system = system;
        this.container = container;
        populateRoleComboBox();
    }

    private void populateRoleComboBox() {
        comboBoxSignUpType.removeAllItems();
//
//        if (system.getNetworkList().isEmpty()) {
//            comboBoxSignUpType.addItem(Business.SignUp.SignUpRequest.SignUpType.Country);
//        } else {
//            for (CountryNetwork cNetwork : system.getNetworkList()) {
//                if (cNetwork.getStateList().isEmpty()) {
//                    comboBoxSignUpType.addItem(Business.SignUp.SignUpRequest.SignUpType.Country);
//                    comboBoxSignUpType.addItem(Business.SignUp.SignUpRequest.SignUpType.State);
//                    return;
//                }
//                else{
//                    for(StateNetwork sNetwork:cNetwork.getStateList()){
//                        if(sNetwork.getEnterpriseDirectory().getEnterpriseList().isEmpty()){
//                            
//                    comboBoxSignUpType.addItem(Business.SignUp.SignUpRequest.SignUpType.Country);
//                    comboBoxSignUpType.addItem(Business.SignUp.SignUpRequest.SignUpType.State);
//                    comboBoxSignUpType.addItem(Business.SignUp.SignUpRequest.SignUpType.Enterprise);
//                    return;
//                        
//                    }
//                        else{
                            for (SignUpRequest.SignUpType e : Business.SignUp.SignUpRequest.SignUpType.values()) {
                                comboBoxSignUpType.addItem(e); 
                                
                        }
//                        return;    
//                    }
//                }
//            }
        }
//                    else if(!system.getNetworkList().isEmpty() && ){
//            for (SignUpRequest.SignUpType e : Business.SignUp.SignUpRequest.SignUpType.values()) {
//                comboBoxSignUpType.addItem(e);
//            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSignUpType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 79, 112));
        jLabel1.setText("Welcome To One Word One Army");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 79, 112));
        jLabel2.setText("Please Select an Option from Below");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        add(comboBoxSignUpType, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 210, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 79, 112));
        jLabel3.setText("Register for Respective Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(71, 79, 112));
        btnSubmit.setText("Register");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 130, 42));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/Volunteer.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 19, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try {
            SignUpType type = (SignUpType) comboBoxSignUpType.getSelectedItem();
            CardLayout layout = (CardLayout) container.getLayout();
            if (type == (SignUpRequest.SignUpType.State)) {
                
                container.add("workArea", new SignUpJPanelState(container, system));
            } else if (type == (SignUpRequest.SignUpType.Country)) {
                container.add("workArea", new SignUpJPanelCountry(container, system));
            } else if (type == (SignUpRequest.SignUpType.Enterprise)) {
                container.add("workArea", new SignUpJPanelEnterprise(container, system));
            } else {
                container.add("workArea", new SignUpJPanel(container, system, type));
            }
            layout.next(container);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboBoxSignUpType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
